name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22 # Change to 21 if using plain FTP, but this action is optimized for SFTP
          local_path: './'
          remote_path: ${{ secrets.REMOTE_PATH }}
          sftp_only: true
          delete_remote_files: false # Safer to keep false initially
